### ISSUE TITLE
Incorrect integration tests appsettings file name for PREPROD

### ISSUE THREAD

**Issue by rootik** [eShopWorld/template-webapi-fabric#21]
/src/content/src/Tests/WebAPIService.Integration.Tests/appsettings.PREP.json should be appsettings.PREPROD.json
Script in VSTS release pipeline parses current stage name and construct file name of it.
So extracted environment names are CI, TEST, PREPROD, SAND, PROD

**Comment by VaclavK** [comment]
@rootik  this is news to me... we actually went from PREPROD to PREP and platform recognizes PREP...

**Comment by RuaidhriMcDonnell** [comment]
i would also think the same rule would apply to the webApi project too? i.e. /src/content/src/WebAPIService/appsettings.PREP.json ?

**Comment by cjfarrelly** [comment]
@VaclavK you won't see it on sierra yet as it doesn't release to preprod/prep

**Comment by VaclavK** [comment]
@cjfarrelly you misunderstand... I am not talking re sierra app deploy, I am talking about pipeline Sierra is coded to produce.... the understanding has been the stage name is PREP... so are we talking the **official** name is PREPROD?

**Comment by dguerin** [comment]
Per side discussion, all agree, all env configs .json or xml should use the shortnames eg PREP, PROD
